/** UI-only copy — warm, short labels. AI chat copy stays in persona/onboarding. */
export const UI_COPY = {
  grid: {
    emptyWardrobe: "Add closet photos to get started.",
    emptyLooks: "Tell me what you're dressing for — your looks will appear here.",
    generating: "Putting a look together…",
  },
  generation: {
    phases: {
      analyzing: "Scanning your closet…",
      selecting: "Choosing pieces for your vibe…",
      finishing: "Putting your look together…",
      rendering: "Styling on your look…",
    },
    renderFailed: "Couldn't finish styling your photo — please try again.",
    renderingHints: [
      "Styling on your look…",
      "Layering your pieces…",
      "Almost dressed…",
      "One more touch…",
    ],
    selectingHints: [
      "Choosing pieces for your vibe…",
      "Trying a few combos…",
      "Balancing colors and fit…",
      "Narrowing to your best look…",
      "Almost there…",
    ],
    steps: ["Scanning closet", "Choosing pieces", "Planning look", "Styling photo"],
  },
  input: {
    placeholder: "What are you dressing for?",
    disabledHint: "Add at least one closet item first",
  },
  masonry: {
    title: "Your looks",
    viewFull: "View full",
    download: "Download",
    closePreview: "Close",
  },
  capture: {
    title: "Add to your closet",
  },
  uploads: {
    sectionTitle: "Upload photos",
    sectionHint: "Add your look and closet items — then ask Chrysty to style you.",
    emptyHint: "Tap a card below to upload your first photos.",
    tapToUpload: "Tap to upload",
    managePhotos: "Tap to manage photos",
    noPhotosYet: "No photos yet — upload below.",
    previewPhoto: "Preview photo",
    closePreview: "Back",
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
    deletePhoto: "Remove photo",
    deletingPhoto: "Removing…",
    fileId: "File ID",
    imageId: "Image ID",
    storagePath: "Storage path",
    yourPhotos: "Your photos",
    body: {
      buttonTitle: "Your look",
      buttonSubtitle: "Body, face, or mannequin — so I can style on you.",
      sheetTitle: "Add your look",
      sheetHint: "Upload a full-body photo, face shot, or mannequin reference.",
      uploadCta: "Upload photos",
      uploading: "Uploading…",
      confirmCta: "Save reference",
      confirming: "Saving…",
      limitReached: "Maximum reached (5)",
    },
    wardrobe: {
      buttonTitle: "Your closet",
      buttonSubtitle: "Tops, bottoms, shoes, and accessories to mix into looks.",
      sheetTitle: "Add closet items",
      sheetHint: "One item per photo works best — label optional.",
      uploadCta: "Upload photos",
      uploading: "Uploading…",
      labelPlaceholder: "Navy crewneck",
      confirmCta: "Confirm item",
      confirming: "Saving…",
      limitReached: "Maximum reached (30)",
    },
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
    label: "Appearance",
  },
  welcome: {
    splash: "Chrysty",
    headline: "Your personal stylist.",
    subhead: "Show me your closet. I'll show you looks.",
    cta: "Get started",
  },
  actions: {
    addClothes: "Add clothes",
  },
  settings: {
    title: "Settings",
    subline: "Your space mission and style profile.",
    openLabel: "Open settings",
    spaceTitle: "This space",
    spaceSubline: "Mission and style profile for this workspace.",
    saveCta: "Save changes",
    saving: "Saving…",
    saved: "Saved",
  },
  workspaces: {
    createTitle: "New space",
    step1Label: "Basics",
    step2Label: "Your style",
    nextCta: "Continue",
    backCta: "Back",
    nameLabel: "Name",
    namePlaceholder: "Work week",
    missionLabel: "Mission",
    missionPlaceholder: "What is this space for? e.g. Client meetings, smart casual",
    createCta: "Create space",
    switchLabel: "Switch space",
    activeLabel: "Current",
    addLabel: "Create new space",
    chips: ["Work week", "Weekend", "Travel"],
    profileValidation: "Answer all three questions to continue.",
    nameMissionRequired: "Name and mission are required.",
  },
  sidebar: {
    openLabel: "Open sidebar",
    closeLabel: "Close sidebar",
  },
  header: {
    subline: "Just you and me",
  },
  greeting: {
    empty: "What are we dressing for?",
  },
  menu: {
    addClothes: "Add clothes",
  },
} as const;
